set_property PACKAGE_PIN W4 [get_ports {on_off}]
set_property PACKAGE_PIN R4 [get_ports {rst}]
set_property PACKAGE_PIN Y18 [get_ports {clk}]
set_property PACKAGE_PIN P5 [get_ports {up_level}]
set_property PACKAGE_PIN P2 [get_ports {down_level}]
set_property PACKAGE_PIN P1 [get_ports {left_level}]
set_property PACKAGE_PIN R1 [get_ports {right_level}]
set_property PACKAGE_PIN T4 [get_ports {ifcharge}]

set_property IOSTANDARD LVCMOS33 [get_ports {on_off}]
set_property IOSTANDARD LVCMOS33 [get_ports {rst}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {up_level}]
set_property IOSTANDARD LVCMOS33 [get_ports {down_level}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_level}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_level}]
set_property IOSTANDARD LVCMOS33 [get_ports {ifcharge}]

set_property IOSTANDARD LVCMOS33 [get_ports {col[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[3]}]
set_property PACKAGE_PIN K6 [get_ports {col[2]}]
set_property PACKAGE_PIN M2 [get_ports {col[3]}]
set_property PACKAGE_PIN J4 [get_ports {row[2]}]
set_property PACKAGE_PIN K4 [get_ports {row[3]}]
set_property PACKAGE_PIN L5 [get_ports {col[0]}]
set_property PACKAGE_PIN J6 [get_ports {col[1]}]
set_property PACKAGE_PIN K3 [get_ports {row[0]}]
set_property PACKAGE_PIN L3 [get_ports {row[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {Y[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Y[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Y[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Y[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Y[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Y[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Y[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Y[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DIG[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DIG[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DIG[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DIG[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DIG[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DIG[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DIG[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DIG[0]}]

set_property PACKAGE_PIN C19 [get_ports {DIG[0]}]
set_property PACKAGE_PIN E19 [get_ports {DIG[1]}]
set_property PACKAGE_PIN D19 [get_ports {DIG[2]}]
set_property PACKAGE_PIN F18 [get_ports {DIG[3]}]
set_property PACKAGE_PIN E18 [get_ports {DIG[4]}]
set_property PACKAGE_PIN B20 [get_ports {DIG[5]}]
set_property PACKAGE_PIN A20 [get_ports {DIG[6]}]
set_property PACKAGE_PIN A18 [get_ports {DIG[7]}]
set_property PACKAGE_PIN F15 [get_ports {Y[0]}]
set_property PACKAGE_PIN F13 [get_ports {Y[1]}]
set_property PACKAGE_PIN F14 [get_ports {Y[2]}]
set_property PACKAGE_PIN F16 [get_ports {Y[3]}]
set_property PACKAGE_PIN E17 [get_ports {Y[4]}]
set_property PACKAGE_PIN C14 [get_ports {Y[5]}]
set_property PACKAGE_PIN C15 [get_ports {Y[6]}]
set_property PACKAGE_PIN E13 [get_ports {Y[7]}]

set_property PACKAGE_PIN A21 [get_ports {charge_end}]
set_property IOSTANDARD LVCMOS33 [get_ports {charge_end}]

set_property IOSTANDARD LVCMOS33 [get_ports beep]
set_property PACKAGE_PIN A19 [get_ports beep]

set_property IOSTANDARD LVCMOS33 [get_ports lookup]
set_property PACKAGE_PIN T5 [get_ports lookup]

set_property IOSTANDARD LVCMOS33 [get_ports middle_level]
set_property PACKAGE_PIN P4 [get_ports middle_level]