# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/vivado/vivadoProjects/CS207_Project/CS207_Project.cache/wt [current_project]
set_property parent.project_path E:/vivado/vivadoProjects/CS207_Project/CS207_Project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/vivado/vivadoProjects/CS207_Project/CS207_Project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/vivado/vivadoProjects/CS207_Project/CS207_Project.srcs/sources_1/new/Bin_BCD.v
  E:/vivado/vivadoProjects/CS207_Project/CS207_Project.srcs/sources_1/new/addr_gen.v
  E:/vivado/vivadoProjects/CS207_Project/CS207_Project.srcs/sources_1/new/auto_off_top.v
  E:/vivado/vivadoProjects/CS207_Project/CS207_Project.srcs/sources_1/new/beep.v
  E:/vivado/vivadoProjects/CS207_Project/CS207_Project.srcs/sources_1/new/charge.v
  E:/vivado/vivadoProjects/CS207_Project/CS207_Project.srcs/sources_1/new/controller_top.v
  E:/vivado/vivadoProjects/CS207_Project/CS207_Project.srcs/sources_1/new/corepower.v
  E:/vivado/vivadoProjects/CS207_Project/CS207_Project.srcs/sources_1/new/coretemper.v
  E:/vivado/vivadoProjects/CS207_Project/CS207_Project.srcs/sources_1/new/countdown_input.v
  E:/vivado/vivadoProjects/CS207_Project/CS207_Project.srcs/sources_1/new/decode.v
  E:/vivado/vivadoProjects/charge_test/div.v
  E:/vivado/vivadoProjects/CS207_Project/CS207_Project.srcs/sources_1/new/div_frequency.v
  E:/vivado/vivadoProjects/CS207_Project/CS207_Project.srcs/sources_1/new/envirtemper_mode.v
  E:/vivado/vivadoProjects/CS207_Project/CS207_Project.srcs/sources_1/new/key_vibration.v
  E:/vivado/vivadoProjects/CS207_Project/CS207_Project.srcs/sources_1/new/keyboard_core.v
  E:/vivado/vivadoProjects/CS207_Project/CS207_Project.srcs/sources_1/new/keyboard_map.v
  E:/vivado/vivadoProjects/CS207_Project/CS207_Project.srcs/sources_1/new/memory.v
  E:/vivado/vivadoProjects/CS207_Project/CS207_Project.srcs/sources_1/new/music_gen.v
  E:/vivado/vivadoProjects/CS207_Project/CS207_Project.srcs/sources_1/new/my_rom.v
  E:/vivado/vivadoProjects/CS207_Project/CS207_Project.srcs/sources_1/new/view_charge.v
  E:/vivado/vivadoProjects/CS207_Project/CS207_Project.srcs/sources_1/new/view_chargehistory.v
  E:/vivado/vivadoProjects/CS207_Project/CS207_Project.srcs/sources_1/new/view_elec.v
  E:/vivado/vivadoProjects/CS207_Project/CS207_Project.srcs/sources_1/new/view_mode.v
  E:/vivado/vivadoProjects/CS207_Project/CS207_Project.srcs/sources_1/new/view_temp.v
  E:/vivado/vivadoProjects/CS207_Project/CS207_Project.srcs/sources_1/new/view_time2.v
  E:/vivado/vivadoProjects/CS207_Project/CS207_Project.srcs/sources_1/new/view_top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/vivado/vivadoProjects/CS207_Project/CS207_Project.srcs/constrs_1/new/cons1.xdc
set_property used_in_implementation false [get_files E:/vivado/vivadoProjects/CS207_Project/CS207_Project.srcs/constrs_1/new/cons1.xdc]


synth_design -top view_top -part xc7a100tfgg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef view_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file view_top_utilization_synth.rpt -pb view_top_utilization_synth.pb"
